dbt_news_analytics:
  target: prod
  outputs:
    prod:
      type: duckdb
      path: "md:ph_news"
      threads: 4
      extensions:
        - motherduck
      settings:
        motherduck_token: "{{ env_var('MOTHERDUCK_TOKEN') }}"

    dev:
      type: duckdb
      path: articles_raw.duckdb  # local DuckDB file for development
      threads: 4