dbt_news_analytics:
  target: dev
  outputs:
    prod:
      type: duckdb
      path: "md:ph_news"
      threads: 4
      extensions:
        - motherduck

    dev:
      type: duckdb
      path: ../articles_raw.duckdb  # local DuckDB file for development
      threads: 4