version: 2

sources:
  - name: ph_news_raw
    database: complete-trees-452014-g4
    schema: ph_news_raw
    tables:
      - name: articles_raw
        description: Raw news articles from scraper

models:
  - name: articles
    description: Staged articles with basic cleaning
    columns:
      - name: id
        description: Unique article identifier
        tests:
          - unique